### ISSUE TITLE
endElement is used in ChatBubble but not passed from ChatWindow

### ISSUE THREAD

**Issue by DevDesai2709** [ConversationalComponents/chat-window-core#17]
Hi @AlexTavor 

**endElement** is used in **ChatBubble** component but was not passed from **ChatWindow** component. Just added **endElement** parameter when passing to the **ChatBubble** component . So that it benefits if anyone wants to have an extra element at the end/bottom of the bubble. Implemented this minor change in https://github.com/ConversationalComponents/chat-window/pull/16
Please review.

Thanks!

**Comment by AlexTavor** [comment]
Closed in #16
